export const getDefaultBookmarks = () => [
  {
    url: 'https://wayflyer.okta.com',
    label: 'Okta Portal',
    imgSrc: '/logos/okta.png',
    tags: ['portals'],
  },
  {
    url: 'https://wayflyer.atlassian.net/jira/software/c/projects/PF/issues/?jql=project%20%3D%20%22PF%22%20and%20type%20%3D%20Epic%20and%20status%20in%20(Ready%2C%20%22In%20Progress%22)%20and%20%22Parent%20Link%22%20in%20(PF-1912%2C%20PF-1893)%0AORDER%20BY%20priority%20DESC',
    label: 'Jira',
    imgSrc: '/logos/jira.jpeg',
    tags: ['ops-tools'],
  },
  {
    url: 'https://docs.wayflyer.io/frontend/latest/',
    label: 'Wayflyer Frontend Docs',
    imgSrc: '/logos/fefo.png',
    tags: ['docs', 'frontend'],
  },
  {
    url: 'https://flyui.wayflyer.com/',
    label: 'Storybook FlyUI',
    imgSrc: '/logos/storybook.png',
    tags: ['dev-tools', 'frontend'],
  },
  {
    url: 'https://main--635a5a0b33dc3e29c1340854.chromatic.com',
    label: 'Storybook Shared-UI',
    imgSrc: '/logos/storybook.png',
    tags: ['dev-tools', 'frontend'],
  },
  {
    url: 'https://main--645a93bddea79441a785fd0f.chromatic.com/',
    label: 'Storybook - Customer App',
    imgSrc: '/logos/storybook.png',
    tags: ['dev-tools', 'frontend'],
  },
  {
    url: 'https://main--645a93d6717e9c486cc370ae.chromatic.com/',
    label: 'Storybook - Staff App',
    imgSrc: '/logos/storybook.png',
    tags: ['dev-tools', 'frontend'],
  },
  {
    url: 'https://main--6389ca48cec250560f8b9ac7.chromatic.com/',
    label: 'Storybook Flyui-Dataviz',
    imgSrc: '/logos/storybook.png',
    tags: ['dev-tools', 'frontend'],
  },
  {
    url: 'https://main--639e00d47c717a573dc14d55.chromatic.com/',
    label: 'Storybook Auth',
    imgSrc: '/logos/storybook.png',
    tags: ['dev-tools', 'frontend'],
  },
  {
    url: 'https://main--66bb6ffeb1a13cd69ad3bb68.chromatic.com',
    label: 'Storybook Banking',
    imgSrc: '/logos/storybook.png',
    tags: ['dev-tools', 'frontend'],
  },
  {
    url: 'https://app.wayflyerdev.com/staff/wayflyercompanies',
    label: 'Wayflyer Staff App - Dev',
    imgSrc: '/logos/wayflyer-dev.png',
    tags: ['dev-tools'],
  },
  {
    url: 'https://app.wayflyer.com/staff/wayflyercompanies',
    label: 'Wayflyer Staff App - Production',
    imgSrc: '/logos/wayflyer.png',
    tags: ['dev-tools', 'ops-tools'],
  },
  {
    url: 'https://app.datadoghq.eu/dashboard/27q-5sc-kcn?from_ts=1663178068714&to_ts=1663181668714&live=true',
    label: 'Datadog Health Dashboard',
    imgSrc: '/logos/datadog.jpeg',
    tags: ['monitoring'],
  },
  {
    url: 'https://www.figma.com/files/1085174594297070258/project/62516860/Design-Kit?fuid=977482556682004509',
    label: 'Figma',
    imgSrc: '/logos/figma.png',
    tags: ['design', 'frontend'],
  },
  {
    url: 'https://app.graphite.dev/',
    label: 'Graphite',
    imgSrc: '/logos/graphite.png',
    tags: ['dev-tools'],
  },
  {
    url: 'https://app.hibob.com/home',
    label: 'HiBob',
    imgSrc: '/logos/hibob.png',
    tags: ['ops-tools'],
  },
  {
    url: 'https://app.hubspot.com/reports-dashboard/6440909/view/8223233',
    label: 'HubSpot',
    imgSrc: '/logos/hubspot.png',
    tags: ['ops-tools'],
  },
  {
    url: 'https://wayflyer.crowdin.com/u/projects/2/l/en',
    label: 'CrowdIn',
    imgSrc: '/logos/crowdin.png',
    tags: ['ops-tools'],
  },
  {
    url: 'https://miro.com/app/dashboard',
    label: 'Miro',
    imgSrc: '/logos/miro.png',
    tags: ['design', 'ops-tools'],
  },
  {
    url: 'https://www.notion.so/wayflyer/Home-201bd7c7db404dcd9ce154879e635961',
    label: 'Notion',
    imgSrc: '/logos/notion.png',
    tags: ['docs'],
  },
  {
    url: 'https://eu-west-1.console.aws.amazon.com/codesuite/codeartifact/d/849891892665/wayflyer/r/wayflyer?region=eu-west-1&packages-meta=eyJmIjp7fSwicyI6e30sIm4iOjIwLCJpIjowfQ',
    label: 'CodeArtifact',
    imgSrc: '/logos/codeartifact.svg',
    tags: ['ops-tools'],
  },
];
